bonding: 0 #选择测试类型,1代表Corosync是bonding，0代表Corosync非bonding
Cycle execution times: 1  #程序循环执行的次数
cluster: <cluster name>
heartbeat_line:
  - 11.11.11.11
  - 22.22.22.22
test_node:  #主要被测节点
  - name: test-n0 #节点名
    ip: 10.203.1.169 #节点ip
    bond_ip: 10.203.2.169  #bondip
    username: root #用户名
    password: password #密码
    bond_name: None  #bond名
    sub_bond_name:
      sub1: None #组成bond的其中一张子网卡名
      sub2: None #组成bond的其中一张子网卡名
  - name: test-n1 #节点名
    ip: 10.203.1.238 #节点ip
    bond_ip: 10.203.2.238  #bondip
    username: root #用户名
    password: password #密码
    bond_name: None  #bond名
    sub_bond_name:
      sub1: None #组成bond的其中一张子网卡名
      sub2: None #组成bond的其中一张子网卡名
  - name: test-n2 #节点名
    ip: 10.203.1.111 #节点ip
    bond_ip: 10.203.2.111  #bondip
    username: root #用户名
    password: password #密码
    bond_name: None  #bond名
    sub_bond_name:
      sub1: None #组成bond的其中一张子网卡名
      sub2: None #组成bond的其中一张子网卡名
other_node: #辅助测试节点（versaplx06）
  - name: None #节点名
    ip: None #节点ip
    username: root #用户名
    password: password #密码
JobNum: 1
BlockSize: 8K   #设置单次生成和写入数据的大小
TotalSize: 10G  #设置写入单个文件/设备的数据总大小
MasterMask: shutdownhxnode1  #block 级测试使用的参数，设置并发写入的线程数（大于0的整数）
DevicePath: /dev/sdb  #device ID 用于生成特定的数据